### ISSUE TITLE
check whether addon adhers to current version of Google's development checklist

### ISSUE THREAD

**Issue by chseifert** [EEXCESS/gdocs-plugin#18]
As can be found here:
https://developers.google.com/apps-script/add-ons/publish

**Comment by kunzstef** [comment]
# Development checklist

## General
- [x] The add-on must be fully functional — it can't be a “work in progress.”
- [x] The script has been tested with multiple active users.
- [x] The design adheres to the UI style guide and doesn't use Material Design or Polymer elements.

## Technical
- [x] The script's project name is the same as the name intended for publication. (The script name appears in the authorization dialog.)
- [x] The script has error-handling code and only shows appropriate error messages to the user.
- [x] The script does not log debug information to the JavaScript console.
- [x] The script includes an onInstall(e) function that populates the menu (usually by calling onOpen(e)).
- [x] To comply with the limitations of the no-authorization mode, the script's global code and the AuthMode.NONE path of the onOpen(e) function should not contain calls to services that require authentication.
- [x] The add-on script has been tested to verify the menus and functionality behave as expected for different states of installed and enabled.
- [x] The script does not use libraries, which can cause the add-on to run slowly.
